# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

arch = ENV["ARCH"]
version = ENV["VERSION"]

Vagrant.configure("2") do |config|
  config.vm.box = "nixos-" + version.to_s + "-virtualbox-iso.virtualbox-03-01" + arch.to_s + ".box"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "4096"
  end

  config.ssh.insert_key = false
end
